sonar.projectKey=Trminh06-work_TaskManager
sonar.organization=trminh06-work
sonar.projectName=TaskManager
sonar.projectVersion=0.1

sonar.sources=server.js,src,views,public
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,reports/**,data/**,public/style.css
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/junit.xml

sonar.sourceEncoding=UTF-8
